import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import { customAuthRouter } from "./customAuth";
import storageRouter from "./storage";
import billingRouter from "./billing";
import organizationsRouter from "./organizations";
import eventsRouter from "./events";
import vendorsRouter from "./vendors";
import sponsorsRouter from "./sponsors";
import contactsRouter from "./contacts";
import statsRouter from "./stats";
import dashboardRouter from "./dashboard";
import sitesRouter from "./sites";
import domainsRouter from "./domains";
import socialRouter from "./social";
import notificationsRouter from "./notifications";
import connectRouter from "./connect";
import adminRouter from "./admin";
import contentRouter from "./content";
import boardLinksRouter from "./boardLinks";
import supportRouter from "./support";
import emailSettingsRouter from "./emailSettings";
import registrationsRouter from "./registrations";
import orgMembersRouter from "./orgMembers";
import siteEngineRouter from "./siteEngine";
import publicContactRouter from "./publicContact";
import managementRouter from "./management";
import publicEventFormsRouter, { publicQueryRouter } from "./publicEventForms";
import eventAdminRouter from "./eventAdmin";
import siteHooksRouter from "./siteHooks";
import publicOrgRouter from "./public";
import serviceApiRouter from "./serviceApi";
import communitySiteRouter from "./communitySite";
import photoAlbumsRouter from "./photoAlbums";
import membersRouter from "./members";
import membersPortalRouter from "./membersPortal";
import announcementsRouter from "./announcements";
import internalMembersRouter from "./internalMembers";
import newsletterRouter from "./newsletter";
import reportsRouter from "./reports";
import operationsRouter from "./operations";
import aiOperationsRouter from "./aiOperations";

const router: IRouter = Router();

router.use(adminRouter);
router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use("/auth", customAuthRouter);
router.use(billingRouter);
router.use(organizationsRouter);
router.use("/events", eventsRouter);
router.use("/vendors", vendorsRouter);
router.use("/sponsors", sponsorsRouter);
router.use("/photo-albums", photoAlbumsRouter);
router.use("/contacts", contactsRouter);
router.use("/stats", statsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/sites", sitesRouter);
router.use("/domains", domainsRouter);
router.use("/social", socialRouter);
router.use("/content", contentRouter);
router.use("/notifications", notificationsRouter);
router.use("/board-links", boardLinksRouter);
router.use(connectRouter);
router.use("/support", supportRouter);
router.use("/email-settings", emailSettingsRouter);
router.use(registrationsRouter);
router.use("/org-members", orgMembersRouter);
router.use("/site-engine", siteEngineRouter);
router.use("/public/contact", publicContactRouter);
router.use("/management", managementRouter);
router.use("/public", publicEventFormsRouter);
router.use(publicQueryRouter);
router.use("/management", eventAdminRouter);
router.use("/hooks", siteHooksRouter);
router.use("/org", publicOrgRouter);
router.use("/service", serviceApiRouter);
router.use("/community-site", communitySiteRouter);
router.use("/members", membersRouter);
router.use("/members-portal", membersPortalRouter);
router.use("/announcements", announcementsRouter);
router.use("/internal", internalMembersRouter);
router.use("/newsletter", newsletterRouter);
router.use("/reports", reportsRouter);
router.use("/operations", operationsRouter);
router.use("/ai", aiOperationsRouter);

export default router;
