import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import storageRouter from "./storage";
import billingRouter from "./billing";
import organizationsRouter from "./organizations";
import eventsRouter from "./events";
import vendorsRouter from "./vendors";
import sponsorsRouter from "./sponsors";
import contactsRouter from "./contacts";
import statsRouter from "./stats";
import sitesRouter from "./sites";
import domainsRouter from "./domains";
import socialRouter from "./social";
import notificationsRouter from "./notifications";
import connectRouter from "./connect";
import adminRouter from "./admin";
import contentRouter from "./content";
import boardLinksRouter from "./boardLinks";

const router: IRouter = Router();

router.use(adminRouter);
router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(billingRouter);
router.use(organizationsRouter);
router.use("/events", eventsRouter);
router.use("/vendors", vendorsRouter);
router.use("/sponsors", sponsorsRouter);
router.use("/contacts", contactsRouter);
router.use("/stats", statsRouter);
router.use("/sites", sitesRouter);
router.use("/domains", domainsRouter);
router.use("/social", socialRouter);
router.use("/content", contentRouter);
router.use("/notifications", notificationsRouter);
router.use("/board-links", boardLinksRouter);
router.use(connectRouter);

export default router;
